### PR TITLE
Fix missing sticker images

### PR DESCRIPTION
**Pull request by Maciej916**
Some sticker images are missing adding `.toLowerCase()` seems to fix the issue

### CODE REVIEW

**Comment by Step7750** [comment]
Sorry for not looking into this earlier. Which sticker images were missing specifically?

**Comment by danieldspx** [comment]
> Sorry for not looking into this earlier. Which sticker images were missing specifically?

I do not think the stickers are missing for this PR. The problem is that if you pass the filename to the `getStickerURL` and any letter is upper case, it wont work because all files in VPK are lower case. So this PR would make the life of anyone using this package easier by not having to know that filename must be all lower case.

**Comment by Step7750** [comment]
If we want to go the case-insensitive route, then the filenames in the vpk should also be converted to all lowercase. There are a couple uppercase letters in some materials afaik and it's a bad assumption that Valve won't add further material paths with upper-case letters.

**Comment by Step7750** [comment]
Closing this PR, but feel free to re-open with the edits if you'd like!

**Pull request closed without merging**
