### PR TITLE
CS2 Support

### PR DESCRIPTION
**Pull request by Flo4604**
This MR changes quite a bit and is considered a breaking change. 

- Support for CS2 due to valve packing the images now.
- Updates all dependencies to latest version / removed some
- Swiches from commonjs to esm
- Added functions to get medal images
- Replaces the way it downloads files via https://github.com/SteamRE/DepotDownloader
- Is using the CLI of https://github.com/ValveResourceFormat/ValveResourceFormat to dump all images locally, from which we can then calculate the sha1 and get the image link.

It would be great if you could let me know if this is something that would get merged, or any feedback on the changes.

### CODE REVIEW

**Comment by Flo4604** [comment]
cc [@Step7750](https://github.com/Step7750)

**Comment by Flo4604** [comment]
> @Flo4604 I think `items_game_cdn.txt` was removed from the game files.
> 
> I was not able to check it. Does this return the new images of the skins and does this include the new weapons?
> 
> I am able to get the [images](https://github.com/ByMykel/CSGO-API/blob/main/public/images/econ/default_generated/leather_handwraps_handwrap_camo_grey_light.png) from the game files but I don't know how the new cdn url looks like. Do you have any idea?

Yeah it 100% seems like the cdn file was removed. 

I myself don't know the new CDN link, but at this point it might be smart to just create a standalone cdn... for people to use. 

I will look into it on the weekend but can't promise anything

**Comment by Flo4604** [comment]
Gonna close it for now due to the added depenencies and the branch not being uptodate with the latest valve changes.

**Comment by ByMykel** [comment]
@Flo4604 

Seems like the cdn works for stickers:

https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/community/community_2024/paper_retro_zeus.6172a59f34c7fa4ce9777cfb5d315cfca5fa059d.png

**Comment by Flo4604** [comment]
> @Flo4604
> 
> Seems like the cdn works for stickers:
> 
> https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/community/community_2024/paper_retro_zeus.6172a59f34c7fa4ce9777cfb5d315cfca5fa059d.png

Hey, yeah the cdn still works for medal most images afaik, medals patches stickers etc, It only seems like weapons are different now. 

The images are still in the game files tho so I assume they just have a different path now.

**Comment by DanielVolosevich** [comment]
@Flo4604
Could you help me out with your implementation?
The application returns a url for stickers, but the sha1 hash it creates seems to be wrong.
How could I fix this?

**Comment by Flo4604** [comment]
> @Flo4604 Could you help me out with your implementation? The application returns a url for stickers, but the sha1 hash it creates seems to be wrong. How could I fix this?

What do you mean by the sha1 seems to be wrong?, please let me know which sticker you are requesting. 
And show the response url you are getting, and what you are excpecting.

**Comment by DanielVolosevich** [comment]
> > @Flo4604 Could you help me out with your implementation? The application returns a url for stickers, but the sha1 hash it creates seems to be wrong. How could I fix this?
> 
> What do you mean by the sha1 seems to be wrong?, please let me know which sticker you are requesting. And show the response url you are getting, and what you are excpecting.

I am requesting this sticker: cologne2015/mousesports
This is the same sticker as in the original documentation, which should return this URL: https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.3e75da497d9f75fa56f463c22db25f29992561ce.png

when calling cdn.getStickerURL:
console.log(cdn.getStickerURL('cologne2015/mousesports', false));
This cdn url is outputted: https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.78b7ea6ab26bef697c9d03ce0b0d3671c05daf2b.png

The only difference between these two urls seems to be the hashed part.
Thank you for actually wanting to help me!

**Comment by Flo4604** [comment]
> > > @Flo4604 Could you help me out with your implementation? The application returns a url for stickers, but the sha1 hash it creates seems to be wrong. How could I fix this?
> > 
> > 
> > What do you mean by the sha1 seems to be wrong?, please let me know which sticker you are requesting. And show the response url you are getting, and what you are excpecting.
> 
> @Flo4604 I am requesting this sticker: cologne2015/mousesports This is the same sticker as in the original documentation, which should return this URL: [steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.3e75da497d9f75fa56f463c22db25f29992561ce.png](https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.3e75da497d9f75fa56f463c22db25f29992561ce.png)
> 
> when calling cdn.getStickerURL: console.log(cdn.getStickerURL('cologne2015/mousesports', false)); This cdn url is outputted: [steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.78b7ea6ab26bef697c9d03ce0b0d3671c05daf2b.png](https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.78b7ea6ab26bef697c9d03ce0b0d3671c05daf2b.png)
> 
> The only difference between these two urls seems to be the hashed part. Thank you for actually wanting to help me!

I'll look into it on the weekend

**Comment by DanielVolosevich** [comment]
> > > > @Flo4604 Could you help me out with your implementation? The application returns a url for stickers, but the sha1 hash it creates seems to be wrong. How could I fix this?
> > > 
> > > 
> > > What do you mean by the sha1 seems to be wrong?, please let me know which sticker you are requesting. And show the response url you are getting, and what you are excpecting.
> > 
> > 
> > @Flo4604 I am requesting this sticker: cologne2015/mousesports This is the same sticker as in the original documentation, which should return this URL: [steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.3e75da497d9f75fa56f463c22db25f29992561ce.png](https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.3e75da497d9f75fa56f463c22db25f29992561ce.png)
> > when calling cdn.getStickerURL: console.log(cdn.getStickerURL('cologne2015/mousesports', false)); This cdn url is outputted: [steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.78b7ea6ab26bef697c9d03ce0b0d3671c05daf2b.png](https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/cologne2015/mousesports.78b7ea6ab26bef697c9d03ce0b0d3671c05daf2b.png)
> > The only difference between these two urls seems to be the hashed part. Thank you for actually wanting to help me!
> 
> I'll look into it on the weekend

Just to add a bit more information:
It was generating the wrong hash becaus it was hashing the vtex_c file, not the png of the sticker.

**Comment by Flo4604** [comment]
@DanielVolosevich Are you using the lastest commit of my own fork or the changes here?

If you are using my fork this has already been fixed.

**Comment by Flo4604** [comment]
@DanielVolosevich Also for your info I just added a cs2 cdn which uploads all cs2 images automatically to a r2 server where they are being cached by cloudflare.

you can load images by their normal path without the hash for example: https://cs2cdn.com/econ/stickers/cologne2015/mousesports.png

you can also use https://github.com/ByMykel/CSGO-API which has their own image extracor

**Comment by DanielVolosevich** [comment]
@Flo4604 add me on discord -> espresso_consumer
I'd like to clarify some things about using your R2 server

**Comment by ilzrv** [comment]
@danieldetijger have you figured out how to get the "basic" and "large" version of the image (for different hash)? Maybe only the larger version is available in CS2?

**Comment by ilzrv** [comment]
Yes, but if I want to use the Steam CDN as https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/paris2023/vita.eec767341d18964b7fea56c9469769ec9ed3e05b.png 

Can't I do it? Maybe @Flo4604 has information about this?

**Comment by danieldetijger** [comment]
@ilzrv yes you can do it, I also managed to do it
Maybe try to reverse engineer https://github.com/Flo4604/cs2-cdn
It's got everything you need afaik

**Comment by ilzrv** [comment]
@danieldetijger I'm not sure, because inside pak01_dir.vpk we don't have stickers with the suffix _large (I have already unpacked this archive).

**Comment by danieldetijger** [comment]
@ilzrv I don't remember how I did it, but it is possible, can't really help you further, maybe try reaching @Flo4604

**Comment by ilzrv** [comment]
@danieldetijger Thanks, let's try to wait for @Flo4604

**Comment by Flo4604** [comment]
> @danieldetijger I'm not sure, because inside pak01_dir.vpk we don't have stickers with the suffix _large (I have already unpacked this archive).


If the image is not in the cs files u cant calculate the hash from it.

Are the default images the large ones?

**Comment by ByMykel** [comment]
> > @danieldetijger I'm not sure, because inside pak01_dir.vpk we don't have stickers with the suffix _large (I have already unpacked this archive).
> 
> If the image is not in the cs files u cant calculate the hash from it.
> 
> Are the default images the large ones?

Do you already know how to get the CDN for the CS2 skins?

**Comment by ilzrv** [comment]
> Are the default images the large ones?

@Flo4604 Yes, the images are large by default

**Comment by Flo4604** [comment]
> > > @danieldetijger I'm not sure, because inside pak01_dir.vpk we don't have stickers with the suffix _large (I have already unpacked this archive).
> 
> > 
> 
> > If the image is not in the cs files u cant calculate the hash from it.
> 
> > 
> 
> > Are the default images the large ones?
> 
> 
> 
> Do you already know how to get the CDN for the CS2 skins?

You mean the ones which were in the items game cdn previously?

**Comment by Flo4604** [comment]
> > Are the default images the large ones?
> 
> 
> 
> @Flo4604 Yes, the images are large by default

And you need the smaller ones? Then I suggest just use the default ones and scaling them to whatever size you need.

**Comment by ilzrv** [comment]
> > > Are the default images the large ones?
> > 
> > 
> > @Flo4604 Yes, the images are large by default
> 
> And you need the smaller ones? Then I suggest just use the default ones and scaling them to whatever size you need.

Scaling didn't help. It seems that CS2 decided to abandon the use of small images and leave only large ones

**Comment by Flo4604** [comment]
> > > > Are the default images the large ones?
> 
> > > 
> 
> > > 
> 
> > > @Flo4604 Yes, the images are large by default
> 
> > 
> 
> > And you need the smaller ones? Then I suggest just use the default ones and scaling them to whatever size you need.
> 
> 
> 
> Scaling didn't help. It seems that CS2 decided to abandon the use of small images and leave only large ones

Not true for all images, for example the medals, pins and others still come with a small image.
 
You could resize the image yourself if u need the stickers smaller.

**Comment by ilzrv** [comment]
> > > > > Are the default images the large ones?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > @Flo4604 Yes, the images are large by default
> > 
> > 
> > > 
> > 
> > 
> > > And you need the smaller ones? Then I suggest just use the default ones and scaling them to whatever size you need.
> > 
> > 
> > Scaling didn't help. It seems that CS2 decided to abandon the use of small images and leave only large ones
> 
> Not true for all images, for example the medals, pins and others still come with a small image.
> 
> You could resize the image yourself if u need the stickers smaller.

If you reduce the image yourself, you will not be able to get the correct hash. For example we have a large image https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/dreamhack/dh_gologo1.9cb84d29f38fe347f001e7057a188696bda6f67b.png and small one https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/dreamhack/dh_gologo1.68779ca946e13bfc97d7ae22f99876564f726342.png how do you get a hash for a small one manually?

**Comment by Flo4604** [comment]
> > > > > > Are the default images the large ones?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > @Flo4604 Yes, the images are large by default
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > And you need the smaller ones? Then I suggest just use the default ones and scaling them to whatever size you need.
> 
> > > 
> 
> > > 
> 
> > > Scaling didn't help. It seems that CS2 decided to abandon the use of small images and leave only large ones
> 
> > 
> 
> > Not true for all images, for example the medals, pins and others still come with a small image.
> 
> > 
> 
> > You could resize the image yourself if u need the stickers smaller.
> 
> 
> 
> If you reduce the image yourself, you will not be able to get the correct hash. For example we have a large image https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/dreamhack/dh_gologo1.9cb84d29f38fe347f001e7057a188696bda6f67b.png and small one https://steamcdn-a.akamaihd.net/apps/730/icons/econ/stickers/dreamhack/dh_gologo1.68779ca946e13bfc97d7ae22f99876564f726342.png how do you get a hash for a small one manually?

I think you misunderstood me, you can get the url for the large image and then resize the large image via an api or code

**Comment by ilzrv** [comment]
> I think you misunderstood me, you can get the url for the large image and then resize the large image via an api or code

Yes, but then you will have to reduce the images on your side and use CDN Steam for small images will not work, right? Only for big ones

**Comment by Flo4604** [comment]
> > I think you misunderstood me, you can get the url for the large image and then resize the large image via an api or code
> 
> 
> 
> Yes, but then you will have to reduce the images on your side and use CDN Steam for small images will not work, right? Only for big ones

You can only use the official steam cdn for the files that are packed within cs2, to my knowledge its not possible to get the links any other way. 

If u need the image smaller, calculate the hash of the file that exists for stickers in this case only the big ones and use for example: https://github.com/lovell/sharp to resize it to your wanted size.

You could also use something like https://images.weserv.nl

**Comment by ilzrv** [comment]
> > > I think you misunderstood me, you can get the url for the large image and then resize the large image via an api or code
> > 
> > 
> > Yes, but then you will have to reduce the images on your side and use CDN Steam for small images will not work, right? Only for big ones
> 
> You can only use the official steam cdn for the files that are packed within cs2, to my knowledge its not possible to get the links any other way.
> 
> If u need the image smaller, calculate the hash of the file that exists for stickers in this case only the big ones and use for example: https://github.com/lovell/sharp to resize it to your wanted size.
> 
> You could also use something like https://images.weserv.nl

Yes, thanks. I just wanted to make sure that Valve removed this feature and left only large pictures for some of the images.

**Pull request closed without merging**
