### PR TITLE
Add Patches Support

### PR DESCRIPTION
**Pull request by namvarii**
Some stickers are stored in econ/patches directory. Fixed to get That Stickers.

### CODE REVIEW

**Comment by danieldspx** [comment]
@Step7750 this PR seems to fix missing stickers. Agents have a special kind of sticker that are located in 'resource/flash/econ/patches'. If you use CSGOFloat-Inspect you will get the material in the `kit.patch_material` (not in the usual `kit.sticker_material`).

I really want to use this library but if this PR does not get merged I will have to fork it just to use the fixed version.

**Comment by danieldspx** [comment]
Also, it seems to me that the PR title is unclear.

**Comment by Step7750** [comment]
I don't think we should be conflating stickers and patches here.

There should be separate a separate method for `getPatchUrl` or similar.

**Comment by danieldspx** [comment]
seems reasonable to me. I will make a PR with that change right away.

**Pull request closed without merging**
